create table USER(user_id int, user_name varchar(50), user_added_date date, user_password varchar(50), user_mobile varchar(50));
create table NOTE(note_id int, note_title varchar(50), note_content varchar(50), note_status varchar(50), note_creation_date date);
create table Category(category_id int, category_name varchar(50), category_descr varchar(50), category_creation_date date, category_creator varchar(50));
create table Reminder(reminder_id int, reminder_name varchar(50), reminder_descr varchar(50), reminder_type varchar(50), reminder_creation_date date, reminder_creator varchar(50) );
create table NoteCategory(notecategory_id int, note_id int, category_id int);
create table NoteReminder(notereminder_id int, note_id int, reminder_id int);
create table UserNote(usernote_id int,user_id int, note_id int);
ALTER table USER add PRIMARY KEY(user_id);
ALTER table NOTE add PRIMARY KEY(note_id);
ALTER table Category add PRIMARY KEY(category_id);
ALTER table Reminder add PRIMARY KEY(reminder_id);
ALTER table NoteCategory ADD PRIMARY KEY(notecategory_id),ADD FOREIGN KEY(note_id) REFERENCES NOTE(note_id),ADD FOREIGN KEY(category_id) REFERENCES Category(category_id);
ALTER table NoteReminder ADD PRIMARY KEY(notereminder_id),ADD FOREIGN KEY(note_id) REFERENCES NOTE(note_id),ADD FOREIGN KEY(reminder_id) REFERENCES Reminder(reminder_id);
ALTER table UserNote ADD PRIMARY KEY(usernote_id),ADD FOREIGN KEY(note_id) REFERENCES NOTE(note_id),ADD FOREIGN KEY(user_id) REFERENCES USER(user_id);
insert into USER() values(1, 'Karan', '08-12-1995', 'karan@123', '8988096789');
insert into USER() values(2, 'Aman', '09-5-1996', 'aman@123', 8877906678);
insert into USER() values(3, 'Gagan', '04-6-1996', 'gagan@123', 9875645376);
insert into USER() values(4, 'Akshit', '03-7-1998', 'akshit@123', 9877656776);
insert into USER() values(5, 'Mohit', '10-8-1993', 'mohit@123', 9997656776);
insert into NOTE() values(1, 'Task 5', 'participate in a race competition', 'Incomplete', '22-03-15');
insert into NOTE() values(2, 'Task 4', 'buy groceries', 'Complete', '22-03-12');
insert into NOTE() values(3, 'Task 3', 'pick sonu from school', 'Complete', '22-03-10');
insert into NOTE() values(4, 'Task 2', 'buy milk from shop', 'Incomplete', '22-03-08');
insert into NOTE() values(5, 'Task 1', 'buy pencils from shop', 'Complete', '22-03-15');
insert into category() values(1, 'Books', 'The Common Wealth of Cricket', '1998-03-10','Ramachandra Guha');
insert into category() values(2, 'Books', 'Manohar Parrikar - Off the Record', '1996-04-10','Waman Subha Prabhu');
insert into category() values(3, 'Books', 'The Little Book of Encouragement', '1992-08-10','Dalai Lama');
insert into category() values(4, 'Books', 'Beautiful Things - A memoir', '1990-09-10','Hunter Biden');
insert into category() values(5, 'Books', 'Right Under Our Nose', '1994-09-15','R.Giridharan');
insert into Reminder() values(1, 'Mobile', 'Good','Electronic', '1990-09-10','Aman');
insert into Reminder() values(2, 'TV', 'Good','Electronic', '1990-09-10','Karan');
insert into Reminder() values(3, 'Fridge', 'Good','Electronic', '1990-09-10','Akshit');
insert into Reminder() values(4, 'Set Top Box', 'Ok','Electronic', '1990-09-10','Jeevan');
insert into Reminder() values(5, 'Fan', 'Good','Electrical', '1990-09-10','Aman');
insert into NoteCategory() values(1,4,2);
insert into NoteCategory() values(2,3,2);
insert into NoteCategory() values(3,1,3);
insert into NoteCategory() values(4,1,4);
insert into NoteCategory() values(5,5,3);
insert into NoteReminder() values(1,2,3);
insert into NoteReminder() values(2,3,4);
insert into NoteReminder() values(3,3,5);
insert into NoteReminder() values(4,5,1);
insert into NoteReminder() values(5,4,2);
insert into UserNote() values(1,1,4);
insert into UserNote() values(2,2,4);
insert into UserNote() values(3,4,5);
insert into UserNote() values(4,4,1);
insert into UserNote() values(5,3,3);
select * from USER where user_id = 3 AND user_password = 'gagan@123';
select * from NOTE ORDER BY note_creation_date;
select * from Category where category_creation_date > '1994-04-10';
select note_id from UserNote where user_id = 2;
update NOTE set note_content = 'Buy pens from shop' where note_id = 5;
select * from NOTE inner join UserNote on NOTE.note_id = UserNote.note_id where UserNote.user_id = 4;
select * from NOTE inner join NoteCategory ON NOTE.note_id = NoteCategory.note_id where NoteCategory.category_id = 2;
select * from Reminder inner join NoteReminder ON Reminder.reminder_id = NoteReminder.reminder_id where NoteReminder.note_id = 3;
select * from Reminder where reminder_id = 2;
insert into NOTE() values(6, 'Task 6', 'buy garments', 'Incomplete', '2022-03-16');
insert into UserNote() values(6,4,6);
insert into NOTE() values(7, 'Task 7','buy car', 'Incomplete','2022-03-16');
insert into NoteCategory() values(6,7,2);
update Reminder inner join NoteReminder ON Reminder.reminder_id = NoteReminder.reminder_id set reminder_name = 'Phone' where NoteReminder.note_id = 3;
delete from UserNote where note_id = 3;
delete from UserCategory where note_id = 3;
delete from NoteReminder where note_id = 3;
delete from NOTE where note_id = 3;
select note_id from NoteCategory where category_id = 2;
delete from NoteCategory where note_id = 4;
delete from UserNote where note_id = 4;
delete from NoteReminder where note_id = 4;
delete from NOTE where note_id = 4;

